include:
  - project: 'we-private/backend/common-ci'
    ref: ci
    file: 'ci-functions/build_image.yml'
  - project: 'we-private/backend/common-ci'
    ref: ci
    file: 'ci-functions/deploy_stages.yml'
  - project: 'we-private/backend/common-ci'
    ref: ci
    file: 'ci-functions/migrations.yml'

variables:
  APP_NAME: push-notifications
  CHART_LIST: "push-notifications-api push-notifications-processor-orders push-notifications-processor-prices push-notifications-sender"
  DB_NAME: push_notifications_rs
  MIGRATION_INIT_CMD: /app/migrate init
  MIGRATION_UP_CMD: /app/migration up
  MIGRATION_DOWN_CMD: /app/migration down

stages:
  - "Build docker image"
  - "Deploy to stage/test/dev"
  - "Migrations-INIT"
  - "Migrations-UP"
  - "Migrations-DOWN"

