[package]
name = "push-notifications-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.0"
serde = { version = "1.0", features = ["derive"] }
waves-rust = "0.2.0"
warp = "0.3"
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0"
envy = "0.4"
thiserror = "1.0"
reqwest = { version = "0.11", features = ["json"] }
wavesexchange_log = { git = "https://github.com/waves-exchange/wavesexchange-rs", tag = "wavesexchange_log/0.5.1" }
wavesexchange_warp = { git = "https://github.com/waves-exchange/wavesexchange-rs", tag = "wavesexchange_warp/0.14.3" }
diesel = { version = "2.0", default-features = false, features = ["postgres", "serde_json", "without-deprecated"] }
diesel_migrations = "2.0"
anyhow = "1.0"
fcm = "0.9"

[lib]
name = "lib"
path = "src/lib/lib.rs"

[[bin]]
name = "migration"
path = "src/bin/migration.rs"

[[bin]]
name = "api"
path = "src/bin/api.rs"

[[bin]]
name = "sender"
path = "src/bin/sender.rs"
