[package]
name = "push-notifications-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.0"
serde = { version = "1.0", features = ["derive"] }
waves-rust = "0.2.0"
warp = "0.3"
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0"

[lib]
name = "app_lib"
path = "src/lib/lib.rs"

[[bin]]
name = "api"
path = "src/bin/api.rs"

[[bin]]
name = "sender"
path = "src/bin/sender.rs"
