[package]
name = "database-migration"
version = "0.0.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
diesel.workspace = true
diesel_migrations.workspace = true

# Local deps
database.workspace = true

[[bin]]
name = "migration"
path = "src/main.rs"
